data collection not tied between source and data tier
pique-media/pique pull request #21
Opened 2016-11-09 18:05 UTC by reoliveira

This is implemented currently for twitter only. Will require some factoring of common behaviour upon introduction of new sources, but it is hard to anticipate exactly what until we do.

2016-11-09 18:06 UTC, reoliveira commented on app/services/content/JavaDataCollector.java
> + * This class interacts with an {@link JavaSource} to collect data through a Java
JavaSource is gone, this should just be Source. Will change

2016-11-09 18:27 UTC, edolinsky commented on app/services/sources/TwitterSource.java
> +		return TWITTER;
source name used for data tier should fall under source namespace, e.g. `"source:twitter"`. Use static fields `SOURCE_NAMESPACE` and `NAMESPACE_DELIMITER` in AbstractDataAccess. Can either change here, or in call to `dataAccess.addNewPosts(...)` in `AbstractDataCollector`.

2016-11-09 18:29 UTC, edolinsky commented on test/JavaDataCollectorTest.java
> +		List<Post> retrieved = data.getAllPosts(collector.getSource().getSourceName());
depending on how you integrate namespaces, be wary of this call

2016-11-09 18:37 UTC, edolinsky commented on app/services/content/AbstractDataCollector.java
> +		return dataAccess.addNewPosts(getSource().getSourceName(), posts);
namespace check (see comment in `Twittersource` below)

2016-11-09 18:42 UTC, edolinsky commented on app/services/sources/TwitterSource.java
>  		Map<String, String> env = System.getenv();
If obtaining 3 or fewer environment variables, It may be best to request individually, as opposed to getting all environment variables.

2016-11-09 18:46 UTC, edolinsky requested changes
Looks great! Just polish up use of namespaces when loading into data tier, and we're good to go.

2016-11-10 00:09 UTC, reoliveira commented on app/services/sources/TwitterSource.java
> +		return TWITTER;
This functionality should be provided by the access layer as it implementation specific and this requirement undocumented in the AbstractDataAccess class. Will create issue.

2016-11-10 00:09 UTC, reoliveira commented on test/JavaDataCollectorTest.java
> +		List<Post> retrieved = data.getAllPosts(collector.getSource().getSourceName());
Eh, this is a test so I think it's okay :)

2016-11-10 00:34 UTC, edolinsky approved these changes

2016-11-10 00:35 UTC, merged